AWSTemplateFormatVersion: "2010-09-09"
Description: A CloudFormation template example demonstrating how to call the AWS SDK.

# Resources declared by this template.
Resources:

  # Definition of the evaluation resource stack.
  EvaluationResourceStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ../../cloudformation.yml

  # A policy allowing to list buckets.
  ResourcePolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: list-buckets
      Roles:
        - !Sub ${EvaluationResourceStack.Outputs.EvaluationRole}
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action: s3:ListAllMyBuckets
            Resource: arn:aws:s3:::*

  # Definition of the resource.
  AsyncResource:
    DependsOn: ResourcePolicy
    Type: Custom::AsyncResource
    Properties:
      ServiceToken: !Sub ${EvaluationResourceStack.Outputs.EvaluationResourceFunctionArn}
      Code: |
        const AWS = require('aws-sdk');

        // Setting the region.
        AWS.config.update({ region: process.env.AWS_REGION });

        // Calling the SDK.
        const res = await new AWS.S3()
          .listBuckets()
          .promise();
        
        // Returning the name of the first bucket in the list.
        return ({ data: res.Buckets[0].Name });

# The outputs to be generated by this template.
Outputs:
  AsyncOutput:
    Value: !GetAtt AsyncResource.data
