AWSTemplateFormatVersion: "2010-09-09"
Description: A custom resource evaluating inline Node.js code directly inside your Cloudformation templates.

# Parameters exposed by this template.
Parameters:

  # The lambda timeout value to apply to the custom resource function.
  Timeout:
    Type: Number
    Default: 300
    Description: The lambda timeout value to apply to the custom resource function.
    MinValue: 1

  # The amount of memory to allocate to the AWS Lambda function.
  MemorySize:
    Type: Number
    Default: 128
    Description: The lambda memory value to apply to the custom resource function.
    MinValue: 128
    MaxValue: 3008

# Parameters exposed by this template.
Resources:

  # The custom resource lambda function definition.
  EvaluationResourceFunction:
    Type: AWS::Lambda::Function
    Properties:
      Handler: index.handler
      Role: !GetAtt EvaluationRole.Arn
      Code: ./lambda/
      Runtime: nodejs14.x
      Timeout: !Ref Timeout
      MemorySize: !Ref MemorySize
      Environment:
        Variables:
          TIMEOUT: !Ref Timeout

  # The IAM role to associate with the custom resurce lambda function.
  EvaluationRole:
    Type: AWS::IAM::Role
    Properties:
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole

# The outputs to be generated by this template.
Outputs:
  Name:
    Description: Cloudformation meta resource stack name
    Value: !Ref AWS::StackName
    Export:
      Name: !Sub ${AWS::StackName}-Name
  EvaluationResourceFunctionArn:
    Description: The meta lambda function ARN.
    Value: !GetAtt EvaluationResourceFunction.Arn
    Export:
      Name: !Sub ${AWS::StackName}-MetaFunctionArn
  EvaluationRole:
    Value: !Ref EvaluationRole
    Export:
      Name: !Sub ${AWS::StackName}-Role
  EvaluationRoleArn:
    Value: !GetAtt EvaluationRole.Arn
    Export:
      Name: !Sub ${AWS::StackName}-RoleArn
