AWSTemplateFormatVersion: "2010-09-09"
Description: A CloudFormation template example demonstrating how to convert given parameters into MD5 and SHA-1 hashes inline into the Cloudformation template.

# Resources declared by this template.
Resources:

  # Definition of the evaluation resource stack.
  EvaluationResourceStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ../../cloudformation.yml

  # Definition of the hash transform resource.
  HashTransformFunction:
    Type: Custom::HashTransformFunction
    Properties:
      ServiceToken: !Sub ${EvaluationResourceStack.Outputs.EvaluationResourceFunctionArn}
      Foo: This is a sample string.
      Bar: This is another sample string.
      Code: |
        const crypto = require('crypto');
        return ({
          FooMd5: crypto.createHash('md5').update(props.Foo).digest("hex"),
          BarMd5: crypto.createHash('md5').update(props.Bar).digest("hex"),
          FooSha1: crypto.createHash('sha1').update(props.Foo).digest("hex"),
          BarSha1: crypto.createHash('sha1').update(props.Bar).digest("hex")
        });

# The outputs to be generated by this template.
Outputs:
  FooMd5:
    Description: The generated MD5 hash for `foo`.
    Value: !Sub ${HashTransformFunction.FooMd5}
    Export:
      Name: !Sub ${AWS::StackName}-FooMd5
  BarMd5:
    Description: The generated MD5 hash for `bar`.
    Value: !Sub ${HashTransformFunction.BarMd5}
    Export:
      Name: !Sub ${AWS::StackName}-BarMd5
  FooSha1:
    Description: The generated SHA-1 hash for `foo`.
    Value: !Sub ${HashTransformFunction.FooSha1}
    Export:
      Name: !Sub ${AWS::StackName}-FooSha1
  BarSha1:
    Description: The generated SHA-1 hash for `bar`.
    Value: !Sub ${HashTransformFunction.BarSha1}
    Export:
      Name: !Sub ${AWS::StackName}-BarSha1
