name: cfn-eval CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    name: Testing cfn-eval
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
    steps:
      - name: Clone repo
        uses: actions/checkout@v2
      
      - name: Install cfn-lint
        run: pip install cfn-lint --user

      - name: Install cfn-nag
        run: sudo gem install cfn-nag
      
      - name: Lint CloudFormation
        run: cfn-lint -i W3002 -t cloudformation.yml

      - name: Assess CloudFormation for Security Issues
        run: cfn_nag_scan --input-path cloudformation.yml
      
      - name: Install Lambda Function Dependencies
        working-directory: ./lambda
        run: npm install

      - name: Lint Lambda Function
        working-directory: ./lambda
        run: npm run lint
      
      - name: Test Lambda Function
        working-directory: ./lambda
        run: npm run test
