name: cfn-eval CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  test:
    name: Testing cfn-eval
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v2
      
      - name: Install cfn-lint
        run: pip install cfn-lint --user

      - name: Install cfn-nag
        run: sudo gem install cfn-nag

