name: cfn-eval CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  test:
    name: Testing cfn-eval
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v2
      
      - name: Install cfn-nag
        run: gem install cfn-nag

